- src/stip/common/const.py
I modified stip-common src for slack integration.
Please check it and accept  it.
> Slack integration (stip-common)

- install_scripts/apache/stip-sns-ssl.conf
I fixed about
> I cannot change icon in "Upload New Picture".
The error message in /var/log/apache2/error_sns.log:
I modified stip-sns-ssl.conf.  So replace stip-sns-ssl.conf at /etc/apache2/sites-available/ and restart apache2 service.
> Fix SNS post bugs.

- install_scripts/apache/stip-rs-ssl.conf
- install_scripts/requirements_rs.txt
> Fix to STIX elevator and slide issues

- docker/stip/Dockerfile
Dockerfileにinstallが必要なmodule(libssl-dev)を追加
> #9 Add apt install module 'libssl-dev'

- install_scripts/requirements_rs.txt
requirements_rs.txtの "stix2-elevator"の下に"stix-validator==2.0.0.dev1" を追加しました。
> #12 Add install module 'stix-validator==2.0.0.dev1'

- src/templates/base.html
for
https://github.com/s-tip/stip-rs/issues/19
> Fix string title for common login page

- install_scripts/requirements_rs.txt
- install_scripts/requirements_sns.txt
stix2-validatorのバージョンにより不具合が発生するためバージョンを指定。
> #15 Fixed to module version 'stix-validator' and 'stix2-validator'

- src/templates/base.html
https://github.com/s-tip/stip-sns/issues/28
- An admin user can only change a role of each user in Configuration > User in Repository System
- We abolish a Configuration > User screen
---
- stip-snsのユーザ画面を廃止してRSのユーザ画面に統一します。
> Review of S-TIP role

- README.md
- setup_rs.sh
I modified setup_rs.sh for #21  as follows:
* Check Ubuntu version before installation
* Select a mongodb package depending on the version
* Update mongodb repository for v4.0
> Update Mongo version & add Ubuntu version check

- src/templates/base.html
Added a tag for importing stip_ajax.js.
> Added a tag for importing stip_ajax.js. (for #27 issue)

- README.md
I have updated links to conference slides in README.
> Add a link to BHUSA 2020 slide

- src/stip/common/__init__.py
- src/stip/common/login.py
> Fixed to two issues.

- src/stip/common/login.py
MultIValueDictKeyError occurred. (https://github.com/s-tip/stip-common/issues/48)
> Modifying MultiIValueDictKeyError

- install_scripts/requirements_rs.txt
- install_scripts/requirements_sns.txt
> Add necessary libraries in requirements.txt

- install_scripts/requirements_rs.txt
> Cannnot communicate with slack beyond a proxy that required authentication. #71

- src/static/js/suggest.js
> white space separation by suggestion.

- src/static/css/bootcamp.css
- src/templates/base.html
> Completion a tag in the post textarea and the title text field.

- src/static/js/caretposition.js
- src/templates/base.html
> Uncaught TypeError occurs in some pages. s-tip/stip-sns#127

- src/static/css/bootcamp.css
- src/templates/base.html
> Support for the suggestion when "Support Multi Languages" is set to Yes when posting SNS.

- src/templates/base.html
I implemented a bulk upload in SNS.
This function enables users to post with attachment files via drag & drops.
> Implemented bulk upload

- docker/docker-compose.yml
- docker/stip/Dockerfile
I modified Dockerfile and docker-compose.yml for using `mongo 4.4` and `ubuntu 20.04` and `python 3.8`.
> Update docker file

- install_scripts/requirements_rs.txt
Issue #91 .
Changed the version when installing pymisp.
> Change the install version of pymisp

- install_scripts/requirements_rs.txt
- src/stip/common/login.py
- src/templates/base.html
- src/templates/cover.html
> For the latest Django library. 

- install_scripts/requirements_rs.txt
- src/stip/common/matching_customizer.py
- src/stip/common/stix_customizer.py
- src/templates/base.html
Implemented STIX Customizer, Explicit Matching and Fuzzy Matching.
> Feature stix customizer

- docker/docker-compose.yml
- docker/docker-compose_arm64.yml
- docker/stip.arm/Dockerfile
- docker/stip/Dockerfile
- setup_rs.sh
- Updated installed mongo and MySQL version
- Support ARM64 CPU architecture
> Prepare for version 2.0 release

- README.md
Add the FIRST conference information on `README.md`.
Please review and approve it.
> Add the conference information

- src/templates/cover.html
> Set autocomplete attribute into the form tag

- src/stip/common/rest_api_auth.py
- src/stip/common/session_config.py
> Security update
